name: 'Get Node.js version'
author: vladislavkovaliov
description: 'Node.js version from package.json'

runs:
  using: 'composite'
  steps:
    - name: Read Node.js version from package.json
      id: node-version
      shell: bash
      run: echo "version=$(node -p "require('./package.json')".engines.node)" >> $GITHUB_OUTPUT