name: 'Setup environment'
author: vladislavkovaliov
description: 'Common setup steps for Continues Integration workflows'

runs:
  using: 'composite'

  steps:
    - name: Get Node.js version
      id: node-version
      uses: ./.github/actions/get-node-version

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.node-version.outputs.version }}
        cache: 'npm'

    - name: Install deps
      shell: bash
      run: npm ci

    - name: Read version from package.json
      id: package-version
      shell: bash
      run: echo "version=$(node -p "require('./package.json').engines.version")" >> $GITHUB_OUTPUT

outputs:
  package-version:
    description: 'Package version from package.json'
    value: ${{ steps.package-version.outputs.version }}