name: Continuos Integration

on:
  push:
    branches:
      - main

jobs:
  env-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/env-setup

  unit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Unit test
        run: npm run test