name: Continuos Integration

on:
  push:
    branches:
      - main

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: vladislavkovaliov/wi-github-actions/.github/actions/get-node-version@main
        id: node-version
        with:
          path: ./package.json

      - name: Unit test
        run: npm run test